version: '3.8'

services:
  web:
    image: your-aspnet-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourPassword"
      ACCEPT_EULA: "Y"