name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: cd ./Backend/VoedselBackend/VoedselASP && ls
    - name: check
      run: ls
    - name: docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: change folder
      run: cd ./Backend/VoedselBackend/ 
    - name: docker build
      run: docker build . --file Dockerfile --tag i507797/s3-gp-order-docker-repo:latest
    - name: docker push
      run: docker push i507797/s3-gp-order-docker-repo:latest 
