name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: cd ./Backend/VoedselBackend/VoedselASP
      run: ls
    - name: check
      run: ls
    - name: Build the Docker image
      run: docker build Backend/VoedselBackend/VoedselASP --file Dockerfile --tag my-image-name:1 
