name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore ./Backend/VoedselBackend/VoedselASP

    - name: Build
      run: dotnet build ./Backend/VoedselBackend/VoedselASP

    - name: Run Unit Tests
      run: dotnet test ./Backend/VoedselBackend/VoedselASP/UnitTests --no-build
